site_name: Комментарии к "Капиталу" К. Маркса
site_author: Д. И. Розенберг
site_description: Комментарии к "Капиталу" К. Маркса
copyright: Д. И. Розенберг<br />Комментарии к "Капиталу" К. Маркса
repo_url: https://github.com/marxlib/rozenberg_comments_capital
repo_name: marxlib/rozenberg_comments_capital

theme:
  name: material
  language: ru
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search:
      lang: ru
  #- social

extra:
  generator: false

markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - index.md
  - intro.md
  - intro-author.md
  - Комментарии к тому 1:
      - volume1/index.md
      - Товар и деньги:
          - volume1/part1/index.md
          - volume1/part1/chapter1.md
